### ISSUE TITLE
`node` not found

### ISSUE THREAD

**Issue by vidstige** [heartsucker/node-deb#31] opened 2017-02-23 14:10 UTC
On linux it seems you need to use `nodejs` everywhere, e.g. for the `npm start` commands, etc, while on the mac `node` is the program to call. What's the best way to handle this? Not code on mac? Create symlink on mac? Create symlink on linux? When to create it? I guess the best way is to create the symlink on Mac as that is dev only if you need deb-packages.... No real issue, just want your thoughts.

**Comment by vidstige** [comment] 2017-02-24 09:22
Hold on. Even if I change all places where _I_ use `node` to `nodejs` other packages still have `node` in them, e.g. Mocha. Adding dependency to `nodejs-legacy` seems to resolve the problem.

**Comment by heartsucker** [comment] 2017-02-24 09:50
Hey @vidstige. Are you attempting to run the files created from `node-deb` on your Mac? I'm not sure what the issue is.

**Comment by vidstige** [comment] 2017-02-24 12:48
Use case is I have two machines - One Mac at home and one Linux box att work. There is also a build server which runs linux. I obviously need Linux to create the deb-package which makes sense. However, I would still like to be able to code on my Mac. So I could change all places inside `package.json` etc that does `node mocha whatever` to `nodejs mocha whatever` to make it work on linux boxes, but that will break on mac. Next step is to create symlink on Mac. However that had some issues, so for now I'm installing `nodejs-legacy` on linux as that seems to be the preffered way of getting a `node` binary to call on linux.

This issue is more of a question for you on how you handle this situation, etc.

I see you automatically depend on `node` on the deb, but then call the `node` binary which is not provided by this package. Perhaps `node-deb` should depend on `nodejs-legacy` instead?

**Comment by heartsucker** [comment] 2017-03-01 09:31
@vidstige If you do a `brew install dpkg fakeroot jq`, you can build it on your Mac. Since you can't actually use `dpkg -i foo.deb` and run a package built by `node-deb` on a Mac, and since `node-deb` itself doesn't use any `node`, `nodejs`, or `npm` commands, I think this problem is on your end and not related to this package. I'm closing this for now, but reopen it if you think I'm wrong.

**Closed by heartsucker** 2017-03-01 09:31 UTC

**Comment by vidstige** [comment] 2017-03-01 11:25
No, this is not a bug in node-deb, but rather a question for you. It's about the node vs nodejs binary name mayham, but I've got a workaround now.

**Comment by heartsucker** [comment] 2017-03-01 11:34
I would just so a `ln -s /usr/bin/node /usr/bin/nodejs` or whatever the paths are. Symlinking should clear everything up.
