### ISSUE TITLE
pure systemd systems

### ISSUE THREAD

**Issue by empierre** [heartsucker/node-deb#16] opened 2016-03-17 15:52 UTC
Hello,

  Ubuntu 15.x need the preset to activate the service on startup, so I have modified my postinst to match it:

  elif hash systemctl 2> /dev/null; then
    if [[ "$init_type" == 'auto' || "$init_type" == 'systemd' ]]; then
      {
        systemctl preset "$service_name.service" && \
	systemctl enable "$service_name.service" && \
        systemctl start "$service_name.service"

**Comment by ehartsuyker** [comment] 2016-03-18 09:00
From the `systemctl` manpages:

```
preset NAME...

    Reset one or more unit files, as specified on the command line, to the defaults configured in the preset policy files. This has the same effect as disable or enable, depending how the unit is listed in the preset files.

    Use --preset-mode= to control whether units shall be enabled and disabled, or only enabled, or only disabled.

    For more information on the preset policy format, see systemd.preset(5). For more information on the concept of presets, please consult the Preset document.
```

So to me this looks like `systemctl enable $service` should cover it. We don't use any `systemd` based OS's at work, and I built support for this as a convenience for everyone else, so I don't have complete knowledge of how it works.

If you can find a link explaining why the `preset` command should be added, I'll look into it further.

**Comment by empierre** [comment] 2016-03-18 09:02
Hello,

  I understand and appreciate your work here. 

  I've bumped in that issue on installing on a ubuntu 15.10, all was fine except it wasn't activated... so service was not started on reboot.

**Comment by ehartsuyker** [comment] 2016-03-18 17:38
Word. I'll see if I can reproduce it on a VM and see if that change fixes it.

**Comment by empierre** [comment] 2016-03-18 17:46
also had issues of npm unpak issues, had to add this to correct the issue:
chown 'www-data:www-data' '/var/www/'
chown -R 'www-data:www-data' '/usr/share/mydomoathome'

npm_install() {
  cd "/usr/share/$1/app"
  if [ -e 'node_modules' ]; then
    rm -rf 'node_modules'
  fi
  sudo -u www-data npm install --production
}

**Comment by heartsucker** [comment] 2016-03-21 13:52
@empierre I tested this on an Ubuntu 15.x VM and a Debian 8 VM, and the services appears to survive the restart with just `systemctl enable` and `systemctl start` in the `postinst` script. I'm marking this as "won't fix." I'm opening a second ticket about the ownership problems on the files.

**Closed by heartsucker** 2016-03-21 13:52 UTC
Labels: improvement

**Comment by empierre** [comment] 2016-03-26 07:24
Looking to literature as other user reports issue on others init system I found this:


  if hash service 2> /dev/null; then
    if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
      service "$service_name" start || echo "${service_name} could not be registered or started"
      service enable "$service_name"
    fi

enable is required to start automatically on next reboot, equivalent here for upstart:


  elif hash start 2> /dev/null; then
    if [[ "$init_type" == 'auto' || "$init_type" == 'upstart' ]]; then
      start "$service_name" || echo "${service_name} could not be registered or started"
      echo ENABLED=1 > "/etc/default/$service_name"
      echo start > "/etc/init/$service_name.override"
    fi

**Comment by empierre** [comment] 2016-03-26 07:27
some user reported this too on PI (don't know if this is PI 1 or 2

pi@domoticzpi ~ $ sudo service mydomoathome status
● mydomoathome.service - MDAH ISS Rest interface for Domoticz to Imperihome
   Loaded: loaded (/etc/systemd/system/mydomoathome.service; **disabled**)
   Active: inactive (dead)
pi@domoticzpi ~ $ sudo service mydomoathome start
